version: '3'
services:
    neural_compression:
      container_name: neural_compression
      build: .
      image: qureshi/ml:1.4
      user: $user_id:$group_id
      working_dir: /home/dockeruser
      stdin_open: true
      volumes:
        - /home/faisal/code:/home/dockeruser/code:rw
      tty: true
      ports: 
        - "11955:8888"
        - "11956:8008"
      group_add:
        - "1010"
        - "video"
      environment:
        - HOME="/home/dockeruser"
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                capabilities: 
                  - gpu
                  - utility
                  - compute
                  - video
